create table if not exists public.lb_records (
    id bigint generated by default as identity primary key,
    record jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.lb_records
    add column if not exists created_by uuid,
    add column if not exists updated_by uuid;

create table if not exists public.ceu_records (
    id bigint generated by default as identity primary key,
    category text not null,
    source_id text not null,
    record jsonb not null default '{}'::jsonb,
    is_deleted boolean not null default false,
    created_by uuid,
    updated_by uuid,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.ceu_records
    add column if not exists category text,
    add column if not exists source_id text,
    add column if not exists record jsonb not null default '{}'::jsonb,
    add column if not exists is_deleted boolean not null default false,
    add column if not exists created_by uuid,
    add column if not exists updated_by uuid,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists ceu_records_category_source_id_unique_idx
on public.ceu_records (category, source_id);

create index if not exists ceu_records_category_updated_at_idx
on public.ceu_records (category, updated_at desc);

create table if not exists public.admin_users (
    id uuid primary key references auth.users (id) on delete cascade,
    email text not null,
    role text not null default 'admin',
    is_active boolean not null default true,
    require_mfa boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint admin_users_role_check check (role in ('admin'))
);

alter table public.admin_users
    add column if not exists email text,
    add column if not exists role text not null default 'admin',
    add column if not exists is_active boolean not null default true,
    add column if not exists require_mfa boolean not null default false,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists admin_users_email_unique_idx
on public.admin_users ((lower(email)));

create table if not exists public.record_audit_logs (
    id bigint generated by default as identity primary key,
    record_id bigint not null,
    action text not null,
    actor_user_id uuid,
    actor_email text,
    old_record jsonb,
    new_record jsonb,
    action_at timestamptz not null default timezone('utc', now()),
    constraint record_audit_logs_action_check check (action in ('INSERT', 'UPDATE', 'DELETE'))
);

create index if not exists record_audit_logs_record_id_idx
on public.record_audit_logs (record_id, action_at desc);

create index if not exists record_audit_logs_actor_user_id_idx
on public.record_audit_logs (actor_user_id, action_at desc);

create table if not exists public.record_attachments (
    id bigint generated by default as identity primary key,
    storage_path text not null,
    original_name text not null,
    mime_type text not null default '',
    size_bytes bigint not null default 0,
    record_id bigint references public.lb_records (id) on delete set null,
    history_entry_id text,
    uploaded_at timestamptz not null default timezone('utc', now()),
    uploaded_by text,
    status text not null default 'temp',
    expires_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint record_attachments_size_check check (size_bytes >= 0),
    constraint record_attachments_status_check check (status in ('temp', 'active', 'orphan'))
);

alter table public.record_attachments
    add column if not exists storage_path text,
    add column if not exists original_name text,
    add column if not exists mime_type text not null default '',
    add column if not exists size_bytes bigint not null default 0,
    add column if not exists record_id bigint references public.lb_records (id) on delete set null,
    add column if not exists history_entry_id text,
    add column if not exists uploaded_at timestamptz not null default timezone('utc', now()),
    add column if not exists uploaded_by text,
    add column if not exists status text not null default 'temp',
    add column if not exists expires_at timestamptz,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists record_attachments_storage_path_unique_idx
on public.record_attachments (storage_path);

create index if not exists record_attachments_record_id_idx
on public.record_attachments (record_id, uploaded_at desc);

create index if not exists record_attachments_history_entry_id_idx
on public.record_attachments (history_entry_id);

create index if not exists record_attachments_status_expires_idx
on public.record_attachments (status, expires_at);

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'record-attachments',
    'record-attachments',
    false,
    15728640,
    array[
        'application/pdf',
        'image/jpeg',
        'image/png',
        'image/webp'
    ]::text[]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create or replace function public.set_lb_record_metadata()
returns trigger
language plpgsql
as $$
begin
    if tg_op = 'INSERT' then
        if new.record is null then
            new.record = '{}'::jsonb;
        end if;
        if new.created_by is null then
            new.created_by = auth.uid();
        end if;
    end if;

    new.updated_by = auth.uid();
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create or replace function public.set_ceu_record_metadata()
returns trigger
language plpgsql
as $$
begin
    if tg_op = 'INSERT' then
        if new.record is null then
            new.record = '{}'::jsonb;
        end if;
        if new.created_by is null then
            new.created_by = auth.uid();
        end if;
    end if;

    new.category = lower(trim(coalesce(new.category, '')));
    new.source_id = trim(coalesce(new.source_id, ''));
    if coalesce(new.record ->> 'id', '') = '' and new.source_id <> '' then
        new.record = jsonb_set(new.record, '{id}', to_jsonb(new.source_id), true);
    end if;
    new.updated_by = auth.uid();
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create or replace function public.set_record_attachment_metadata()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    if tg_op = 'INSERT' then
        if new.uploaded_at is null then
            new.uploaded_at = timezone('utc', now());
        end if;
        if new.created_at is null then
            new.created_at = timezone('utc', now());
        end if;
    end if;

    if coalesce(trim(new.uploaded_by), '') = '' then
        new.uploaded_by = nullif(auth.jwt() ->> 'email', '');
    end if;

    if new.status = 'active' then
        new.expires_at = null;
    elsif new.expires_at is null then
        new.expires_at = timezone('utc', now()) + interval '24 hours';
    end if;

    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create or replace function public.log_lb_record_audit()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    insert into public.record_audit_logs (
        record_id,
        action,
        actor_user_id,
        actor_email,
        old_record,
        new_record
    )
    values (
        case when tg_op = 'DELETE' then old.id else new.id end,
        tg_op,
        auth.uid(),
        nullif(auth.jwt() ->> 'email', ''),
        case when tg_op in ('UPDATE', 'DELETE') then old.record else null end,
        case when tg_op in ('INSERT', 'UPDATE') then new.record else null end
    );

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

create or replace function public.is_active_admin(user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_users admin_user
        where admin_user.id = user_id
          and admin_user.is_active
    );
$$;

create or replace function public.has_admin_record_access(user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_users admin_user
        where admin_user.id = user_id
          and admin_user.is_active
          and (
              not admin_user.require_mfa
              or coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
          )
    );
$$;

create or replace function public.upsert_admin_user(
    admin_email text,
    admin_role text default 'admin',
    admin_is_active boolean default true,
    admin_require_mfa boolean default false
)
returns public.admin_users
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    normalized_email text;
    target_user_id uuid;
    admin_row public.admin_users;
begin
    normalized_email = lower(trim(admin_email));

    if normalized_email is null or normalized_email = '' then
        raise exception 'Admin email is required.';
    end if;

    select auth_user.id
    into target_user_id
    from auth.users auth_user
    where lower(auth_user.email) = normalized_email
    order by auth_user.created_at desc
    limit 1;

    if target_user_id is null then
        raise exception 'No Supabase Auth user found for %.', normalized_email;
    end if;

    insert into public.admin_users (
        id,
        email,
        role,
        is_active,
        require_mfa
    )
    values (
        target_user_id,
        normalized_email,
        coalesce(nullif(trim(admin_role), ''), 'admin'),
        admin_is_active,
        admin_require_mfa
    )
    on conflict (id) do update
    set
        email = excluded.email,
        role = excluded.role,
        is_active = excluded.is_active,
        require_mfa = excluded.require_mfa,
        updated_at = timezone('utc', now());

    select *
    into admin_row
    from public.admin_users
    where id = target_user_id;

    return admin_row;
end;
$$;

drop trigger if exists lb_records_set_metadata on public.lb_records;
create trigger lb_records_set_metadata
before insert or update on public.lb_records
for each row
execute function public.set_lb_record_metadata();

drop trigger if exists ceu_records_set_metadata on public.ceu_records;
create trigger ceu_records_set_metadata
before insert or update on public.ceu_records
for each row
execute function public.set_ceu_record_metadata();

drop trigger if exists admin_users_set_updated_at on public.admin_users;
create trigger admin_users_set_updated_at
before update on public.admin_users
for each row
execute function public.set_updated_at();

drop trigger if exists record_attachments_set_metadata on public.record_attachments;
create trigger record_attachments_set_metadata
before insert or update on public.record_attachments
for each row
execute function public.set_record_attachment_metadata();

drop trigger if exists lb_records_write_audit_log on public.lb_records;
create trigger lb_records_write_audit_log
after insert or update or delete on public.lb_records
for each row
execute function public.log_lb_record_audit();

alter table public.lb_records enable row level security;
alter table public.ceu_records enable row level security;
alter table public.admin_users enable row level security;
alter table public.record_audit_logs enable row level security;
alter table public.record_attachments enable row level security;

drop policy if exists "Admin users can read their own profile" on public.admin_users;
create policy "Admin users can read their own profile"
on public.admin_users
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Approved admin users can read Lingkod Bayan records" on public.lb_records;
create policy "Approved admin users can read Lingkod Bayan records"
on public.lb_records
for select
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can insert Lingkod Bayan records" on public.lb_records;
create policy "Approved admin users can insert Lingkod Bayan records"
on public.lb_records
for insert
to authenticated
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can update Lingkod Bayan records" on public.lb_records;
create policy "Approved admin users can update Lingkod Bayan records"
on public.lb_records
for update
to authenticated
using (public.has_admin_record_access(auth.uid()))
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can delete Lingkod Bayan records" on public.lb_records;
create policy "Approved admin users can delete Lingkod Bayan records"
on public.lb_records
for delete
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can read CEU records" on public.ceu_records;
create policy "Approved admin users can read CEU records"
on public.ceu_records
for select
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can insert CEU records" on public.ceu_records;
create policy "Approved admin users can insert CEU records"
on public.ceu_records
for insert
to authenticated
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can update CEU records" on public.ceu_records;
create policy "Approved admin users can update CEU records"
on public.ceu_records
for update
to authenticated
using (public.has_admin_record_access(auth.uid()))
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can delete CEU records" on public.ceu_records;
create policy "Approved admin users can delete CEU records"
on public.ceu_records
for delete
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can read record audit logs" on public.record_audit_logs;
create policy "Approved admin users can read record audit logs"
on public.record_audit_logs
for select
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can read record attachments" on public.record_attachments;
create policy "Approved admin users can read record attachments"
on public.record_attachments
for select
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can insert record attachments" on public.record_attachments;
create policy "Approved admin users can insert record attachments"
on public.record_attachments
for insert
to authenticated
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can update record attachments" on public.record_attachments;
create policy "Approved admin users can update record attachments"
on public.record_attachments
for update
to authenticated
using (public.has_admin_record_access(auth.uid()))
with check (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can delete record attachments" on public.record_attachments;
create policy "Approved admin users can delete record attachments"
on public.record_attachments
for delete
to authenticated
using (public.has_admin_record_access(auth.uid()));

drop policy if exists "Approved admin users can view attachment objects" on storage.objects;
create policy "Approved admin users can view attachment objects"
on storage.objects
for select
to authenticated
using (
    bucket_id = 'record-attachments'
    and public.has_admin_record_access(auth.uid())
);

drop policy if exists "Approved admin users can upload attachment objects" on storage.objects;
create policy "Approved admin users can upload attachment objects"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'record-attachments'
    and public.has_admin_record_access(auth.uid())
);

drop policy if exists "Approved admin users can update attachment objects" on storage.objects;
create policy "Approved admin users can update attachment objects"
on storage.objects
for update
to authenticated
using (
    bucket_id = 'record-attachments'
    and public.has_admin_record_access(auth.uid())
)
with check (
    bucket_id = 'record-attachments'
    and public.has_admin_record_access(auth.uid())
);

drop policy if exists "Approved admin users can delete attachment objects" on storage.objects;
create policy "Approved admin users can delete attachment objects"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'record-attachments'
    and public.has_admin_record_access(auth.uid())
);

do $$
begin
    begin
        alter publication supabase_realtime add table public.lb_records;
    exception
        when duplicate_object then null;
    end;

    begin
        alter publication supabase_realtime add table public.ceu_records;
    exception
        when duplicate_object then null;
    end;
end;
$$;

-- After creating the Supabase Auth user, register the real admin account:
-- select public.upsert_admin_user('cnlajarastaff@gmail.com', 'admin', true, false);
-- select public.upsert_admin_user('karlmatthewdegala@gmail.com', 'admin', true, false);
--
-- To populate the CEU Database through the Supabase SQL Editor, run every file in
-- supabase/ceu-seed-parts after this setup file, from part 01 through part 12.
-- The seed files use ON CONFLICT DO NOTHING so existing CEU rows are preserved.
--
-- The scheduled cleanup job lives in supabase/functions/cleanup-record-attachments.
-- Run it on a daily or every-few-hours schedule with the Supabase cron / scheduled functions UI.
